apiVersion: team.crossplane.io/v1alpha1
kind: Membership
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/membership
  labels:
    testing.upbound.io/example-name: some_team_membership
  name: some-team-membership
spec:
  forProvider:
    role: member
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: some_team
    username: SomeUser

---

apiVersion: team.crossplane.io/v1alpha1
kind: Membership
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/membership
  labels:
    testing.upbound.io/example-name: membership_for_some_user
  name: membership-for-some-user
spec:
  forProvider:
    role: member
    username: SomeUser

---

apiVersion: team.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/membership
  labels:
    testing.upbound.io/example-name: some_team
  name: some-team
spec:
  forProvider:
    description: Some cool team
    name: SomeTeam
