apiVersion: repo.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deploymentBranchPolicy:
    - customBranchPolicies: false
      protectedBranches: true
    environment: example
    preventSelfReview: true
    reviewers:
    - users:
      - ${data.github_user.current.id}

---

apiVersion: repo.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My awesome codebase
    name: A Repository Project
