// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Branch) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchProtection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchProtectionV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeployKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *File) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PullRequest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryAutolinkReference) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryWebhook) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ruleset) Hub() {}
