// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LabelsInitParameters struct {

	// List of labels
	Label []LabelsLabelInitParameters `json:"label,omitempty" tf:"label,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

type LabelsLabelInitParameters struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the label.
	// The name of the label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LabelsLabelObservation struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the label.
	// The name of the label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Computed) The URL to the issue label
	// The URL to the issue label.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type LabelsLabelParameters struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	// +kubebuilder:validation:Optional
	Color *string `json:"color" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the label.
	// The name of the label.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type LabelsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels
	Label []LabelsLabelObservation `json:"label,omitempty" tf:"label,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

type LabelsParameters struct {

	// List of labels
	// +kubebuilder:validation:Optional
	Label []LabelsLabelParameters `json:"label,omitempty" tf:"label,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

// LabelsSpec defines the desired state of Labels
type LabelsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LabelsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LabelsInitParameters `json:"initProvider,omitempty"`
}

// LabelsStatus defines the observed state of Labels.
type LabelsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LabelsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Labels is the Schema for the Labelss API. Provides GitHub issue labels resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,github}
type Labels struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repository) || (has(self.initProvider) && has(self.initProvider.repository))",message="spec.forProvider.repository is a required parameter"
	Spec   LabelsSpec   `json:"spec"`
	Status LabelsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LabelsList contains a list of Labelss
type LabelsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Labels `json:"items"`
}

// Repository type metadata.
var (
	Labels_Kind             = "Labels"
	Labels_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Labels_Kind}.String()
	Labels_KindAPIVersion   = Labels_Kind + "." + CRDGroupVersion.String()
	Labels_GroupVersionKind = CRDGroupVersion.WithKind(Labels_Kind)
)

func init() {
	SchemeBuilder.Register(&Labels{}, &LabelsList{})
}
