// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LabelInitParameters struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the label.
	// The name of the label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

type LabelObservation struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the label.
	// The name of the label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// (Computed) The URL to the issue label
	// The URL to the issue label.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type LabelParameters struct {

	// A 6 character hex code, without the leading #, identifying the color of the label.
	// A 6 character hex code, without the leading '#', identifying the color of the label.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// A short description of the label.
	// A short description of the label.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the label.
	// The name of the label.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The GitHub repository
	// The GitHub repository.
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

// LabelSpec defines the desired state of Label
type LabelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LabelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LabelInitParameters `json:"initProvider,omitempty"`
}

// LabelStatus defines the observed state of Label.
type LabelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LabelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Label is the Schema for the Labels API. Provides a GitHub issue label resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,github}
type Label struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.color) || (has(self.initProvider) && has(self.initProvider.color))",message="spec.forProvider.color is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repository) || (has(self.initProvider) && has(self.initProvider.repository))",message="spec.forProvider.repository is a required parameter"
	Spec   LabelSpec   `json:"spec"`
	Status LabelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LabelList contains a list of Labels
type LabelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Label `json:"items"`
}

// Repository type metadata.
var (
	Label_Kind             = "Label"
	Label_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Label_Kind}.String()
	Label_KindAPIVersion   = Label_Kind + "." + CRDGroupVersion.String()
	Label_GroupVersionKind = CRDGroupVersion.WithKind(Label_Kind)
)

func init() {
	SchemeBuilder.Register(&Label{}, &LabelList{})
}
