---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.jsonn
name: Terraform Provider Update Check

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

env:
  PROVIDER_NAME: github # Replace with your upstream provider name
  CROSSPLANE_PROVIDER_NAME: provider-github # Replace with your Crossplane provider name

jobs:
  check-terraform-provider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Get latest Terraform provider version
        id: tf-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform-provider-${{ env.PROVIDER_NAME }}/releases/latest | jq -r .tag_name | sed 's/v//')
          echo "::set-output name=version::$LATEST_VERSION"

      - name: Check current version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=Version = ")[^"]*' provider/provider.go)
          echo "::set-output name=version::$CURRENT_VERSION"

      - name: Compare versions
        id: version-compare
        run: |
          if [ "${{ steps.tf-version.outputs.version }}" != "${{ steps.current-version.outputs.version }}" ]; then
            echo "::set-output name=update_needed::true"
          else
            echo "::set-output name=update_needed::false"
          fi

      - name: Update provider version
        if: steps.version-compare.outputs.update_needed == 'true'
        run: |
          sed -i 's/Version = ".*"/Version = "${{ steps.tf-version.outputs.version }}"/' provider/provider.go

      - name: Generate Crossplane resources
        if: steps.version-compare.outputs.update_needed == 'true'
        run: |
          go run ./cmd/generator/main.go

      - name: Check for unsupported resources
        if: steps.version-compare.outputs.update_needed == 'true'
        id: unsupported-resources
        run: |
          UNSUPPORTED=$(go run ./cmd/generator/main.go --list-unsupported)
          echo "::set-output name=list::$UNSUPPORTED"

      - name: Create Pull Request
        if: steps.version-compare.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update ${{ env.CROSSPLANE_PROVIDER_NAME }} to version ${{ steps.tf-version.outputs.version }}"
          title: "Update ${{ env.CROSSPLANE_PROVIDER_NAME }} to version ${{ steps.tf-version.outputs.version }}"
          body: |
            This PR updates the ${{ env.CROSSPLANE_PROVIDER_NAME }} to version ${{ steps.tf-version.outputs.version }}.

            Unsupported resources:
            ```
            ${{ steps.unsupported-resources.outputs.list }}
            ```
          branch: update-provider-version
          base: main
